/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAutomationRouteImport } from './routes/app.automation'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppEventaiRouteImport } from './routes/app.eventai'
import { Route as AppFeedbackaiRouteImport } from './routes/app.feedbackai'
import { Route as AppModulesRouteImport } from './routes/app.modules'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppQueueaiRouteImport } from './routes/app.queueai'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppWorkspacesRouteImport } from './routes/app.workspaces'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as PublicSlugRouteImport } from './routes/public.$slug'
import { Route as TicketTokenRouteImport } from './routes/ticket.$token'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api.webhooks.whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEventaiRoute = AppEventaiRouteImport.update({
  id: '/eventai',
  path: '/eventai',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackaiRoute = AppFeedbackaiRouteImport.update({
  id: '/feedbackai',
  path: '/feedbackai',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRoute = AppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueaiRoute = AppQueueaiRouteImport.update({
  id: '/queueai',
  path: '/queueai',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSlugRoute = PublicSlugRouteImport.update({
  id: '/public/$slug',
  path: '/public/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTokenRoute = TicketTokenRouteImport.update({
  id: '/ticket/$token',
  path: '/ticket/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/eventai': typeof AppEventaiRoute
  '/app/feedbackai': typeof AppFeedbackaiRoute
  '/app/modules': typeof AppModulesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/queueai': typeof AppQueueaiRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/e/$slug': typeof ESlugRoute
  '/f/$token': typeof FTokenRoute
  '/join/$slug': typeof JoinSlugRoute
  '/public/$slug': typeof PublicSlugRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/eventai': typeof AppEventaiRoute
  '/app/feedbackai': typeof AppFeedbackaiRoute
  '/app/modules': typeof AppModulesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/queueai': typeof AppQueueaiRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/e/$slug': typeof ESlugRoute
  '/f/$token': typeof FTokenRoute
  '/join/$slug': typeof JoinSlugRoute
  '/public/$slug': typeof PublicSlugRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/app': typeof AppIndexRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/eventai': typeof AppEventaiRoute
  '/app/feedbackai': typeof AppFeedbackaiRoute
  '/app/modules': typeof AppModulesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/queueai': typeof AppQueueaiRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/e/$slug': typeof ESlugRoute
  '/f/$token': typeof FTokenRoute
  '/join/$slug': typeof JoinSlugRoute
  '/public/$slug': typeof PublicSlugRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/verify-email'
    | '/app/analytics'
    | '/app/automation'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/eventai'
    | '/app/feedbackai'
    | '/app/modules'
    | '/app/notifications'
    | '/app/queueai'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/workspaces'
    | '/e/$slug'
    | '/f/$token'
    | '/join/$slug'
    | '/public/$slug'
    | '/ticket/$token'
    | '/app/'
    | '/api/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/verify-email'
    | '/app/analytics'
    | '/app/automation'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/eventai'
    | '/app/feedbackai'
    | '/app/modules'
    | '/app/notifications'
    | '/app/queueai'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/workspaces'
    | '/e/$slug'
    | '/f/$token'
    | '/join/$slug'
    | '/public/$slug'
    | '/ticket/$token'
    | '/app'
    | '/api/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/verify-email'
    | '/app/analytics'
    | '/app/automation'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/eventai'
    | '/app/feedbackai'
    | '/app/modules'
    | '/app/notifications'
    | '/app/queueai'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/workspaces'
    | '/e/$slug'
    | '/f/$token'
    | '/join/$slug'
    | '/public/$slug'
    | '/ticket/$token'
    | '/app/'
    | '/api/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ESlugRoute: typeof ESlugRoute
  FTokenRoute: typeof FTokenRoute
  JoinSlugRoute: typeof JoinSlugRoute
  PublicSlugRoute: typeof PublicSlugRoute
  TicketTokenRoute: typeof TicketTokenRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automation': {
      id: '/app/automation'
      path: '/automation'
      fullPath: '/app/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eventai': {
      id: '/app/eventai'
      path: '/eventai'
      fullPath: '/app/eventai'
      preLoaderRoute: typeof AppEventaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedbackai': {
      id: '/app/feedbackai'
      path: '/feedbackai'
      fullPath: '/app/feedbackai'
      preLoaderRoute: typeof AppFeedbackaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/modules': {
      id: '/app/modules'
      path: '/modules'
      fullPath: '/app/modules'
      preLoaderRoute: typeof AppModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queueai': {
      id: '/app/queueai'
      path: '/queueai'
      fullPath: '/app/queueai'
      preLoaderRoute: typeof AppQueueaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspaces': {
      id: '/app/workspaces'
      path: '/workspaces'
      fullPath: '/app/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$slug': {
      id: '/public/$slug'
      path: '/public/$slug'
      fullPath: '/public/$slug'
      preLoaderRoute: typeof PublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$token': {
      id: '/ticket/$token'
      path: '/ticket/$token'
      fullPath: '/ticket/$token'
      preLoaderRoute: typeof TicketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventaiRoute: typeof AppEventaiRoute
  AppFeedbackaiRoute: typeof AppFeedbackaiRoute
  AppModulesRoute: typeof AppModulesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppQueueaiRoute: typeof AppQueueaiRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventaiRoute: AppEventaiRoute,
  AppFeedbackaiRoute: AppFeedbackaiRoute,
  AppModulesRoute: AppModulesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppQueueaiRoute: AppQueueaiRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ESlugRoute: ESlugRoute,
  FTokenRoute: FTokenRoute,
  JoinSlugRoute: JoinSlugRoute,
  PublicSlugRoute: PublicSlugRoute,
  TicketTokenRoute: TicketTokenRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
